#!/bin/bash
#
# Init file for the production DB Relay copy
#
# chkconfig: 345 55 25
# description: DB Relay DB access server
#
# config: /home/dbrelay/conf/nginx.conf
# pidfile: /home/dbrelay/logs/nginx.pid

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
DBRELAY="dbrelay"
HOMEDIR="/home"
DBR_DIR=${HOMEDIR}/${DBRELAY}

start()
{
  echo -n $"Starting DB Relay: "

  # The following line to be used when listening on an unprivileded port (above 1024)
  su -l ${DBRELAY} -c "cd ${DBR_DIR}; ./sbin/nginx --clean && ./sbin/nginx"

  # Uncomment the following line to be used when listening on a privileded port (below 1024)
  # ( cd ${DBR_DIR}; ./sbin/nginx --clean && ./sbin/nginx ) # must run as root to get port 80

  # Only one of the two startup lines above should be used at a time. Also, make sure to set
  # the appropriate "username" and "listen" directives in nginx.conf if listening
  # on privileged ports.

  RETVAL=$?
  [ "$RETVAL" = 0 ] && touch /var/lock/subsys/${DBRELAY}
  pushd ${DBR_DIR} >/dev/null
    [ -d logs_archive ] &&
    cd logs_archive &&
    nohup /bin/bash -c '
      for log in *.tmp
      do
        [ ${log} == "*.tmp" ] && break
        Log2zip=${log%.tmp}
        mv ${log} ${Log2zip}
        tar czf ${Log2zip}.tgz ${Log2zip} && rm -rf ${Log2zip}
      done
      CUTOFF=$(date -d "20 days ago" +%y%m%d000000)
      for file in [1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].t?z
      do
        DATE=${file%.t?z};
        if [ ${DATE} -le ${CUTOFF} ]; then
          rm -f ${file};
        fi
      done
    ' &
  popd >/dev/null
  echo
}

stop()
{
  echo -n $"Stopping DB Relay: "
  PROC_PID=$(cat ${DBR_DIR}/logs/nginx.pid)
  kill ${PROC_PID} &&
  sleep 1 &&
  [ "$(ps p ${PROC_PID} --ppid ${PROC_PID} h o pid,args | wc -l)" -gt 0 ] && sleep 5
  pushd ${DBR_DIR} >/dev/null
    [ -d logs_archive ] || ( mkdir logs_archive && chown ${DBRELAY}:dbrelay logs_archive )
    mv logs logs_archive/$(date +%y%m%d%H%M%S).tmp
    mkdir logs
    chmod ug=rwx,o=rx logs
    chown ${DBRELAY}:dbrelay logs
  popd >/dev/null
  su -l ${DBRELAY} -c "cd ${DBR_DIR}; ./sbin/nginx --clean"
  RETVAL=$?
  [ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/${DBRELAY}
  echo
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    RETVAL=1
esac
exit $RETVAL
