#!/bin/bash

set -e

GIT_TAG=${1}
PKG_PATH=${2}

if [ "${GIT_TAG}" = "" -o "${PKG_PATH}" = "" ]; then
  echo "Syntax: ${0} <tag> <path>"
  echo "        The result will be written out to <path>/viaduct_<tag>.tgz"
  exit 1
fi

BUILD_FILE="viaduct_${GIT_TAG}"
BUILD_DIR="${PKG_PATH}/${BUILD_FILE}"

mkdir ${BUILD_DIR} || {
  echo "Unable to create the package directory: ${BUILD_DIR}"
  exit 1
}


BUILD_TGZ="${BUILD_DIR}.tgz"
VER_FILE="${BUILD_DIR}/html/version.json"

pushd $(dirname ${0})/.. > /dev/null

git archive --format=tar ${GIT_TAG} . | (cd ${BUILD_DIR}; tar xfp -)

git log -n 1 ${GIT_TAG} --pretty=format:"{ 'committer': '%an', 'tag': '${GIT_TAG}', 'revision': '%H', 'date_rfc': '%cD', 'date_epoc': '%ct' }" > ${VER_FILE}

pushd ${PKG_PATH} > /dev/null

tar -czf ${BUILD_TGZ} --owner=0 --group=0 --numeric-owner ./${BUILD_FILE}
rm -rf ./${BUILD_FILE}

popd > /dev/null
popd > /dev/null
