#!/bin/bash

set -e

GIT_TAG=${1}
PKG_PATH=${2}

if [ "${GIT_TAG}" = "" -o "${PKG_PATH}" = "" ]; then
  echo "Syntax: ${0} <tag> <path>"
  echo "        The result will be written out to <path>/viaduct_<tag>.tgz"
  exit 1
fi

BUILD_FILE="${PKG_PATH}/viaduct_${GIT_TAG}"
BUILD_TAR="${BUILD_FILE}.tar"
BUILD_TGZ="${BUILD_FILE}.tgz"
VER_FILE="html/version.json"

pushd $(dirname ${0})/.. > /dev/null

git archive --format=tar ${GIT_TAG} . > ${BUILD_TAR}

git log -n 1 ${GIT_TAG} --pretty=format:"{ 'committer': '%an', 'tag': '${GIT_TAG}', 'revision': '%H', 'date_rfc': '%cD', 'date_epoc': '%ct' }" > ${VER_FILE}

tar -rf ${BUILD_TAR} --owner=0 --group=0 --numeric-owner --remove-files ${VER_FILE}

gzip -c ${BUILD_TAR} > ${BUILD_TGZ}
rm ${BUILD_TAR}

popd > /dev/null
