#!/bin/bash

set -e

[ "${1}" ] || {
  echo "Syntax: ${0} <path>"
  echo "        The result will be written out to <path>/${PREFIX}_<COMMIT_DATE>.tgz"
  exit 1
}

pushd ${1} > /dev/null
  PKG_PATH=${PWD}
popd > /dev/null

PREFIX="dbrelay"
SUBMODULE_PATH="src/ngx_dbrelay"

pushd $(dirname ${0})/.. > /dev/null

  SUBMODULE_SHA=$(git submodule src/ngx_dbrelay | sed -e 's/^.\([^ ]*\) .*$/\1/')
  COMMIT_DATE=$(git log -n 1 --pretty=format:"%ci" | sed -e 's/ .*//' -e 's/-//g' -e 's/^20//')

  GIT_TAG=$(git rev-parse HEAD)
  BUILD_FILE="${PREFIX}_${COMMIT_DATE}"
  BUILD_DIR="${PKG_PATH}/${BUILD_FILE}"

  mkdir ${BUILD_DIR} || {
    echo "Unable to create the package directory: ${BUILD_DIR}"
    exit 1
  }

  BUILD_TGZ="${BUILD_DIR}.tgz"
  VER_FILE="${BUILD_DIR}/html/version.json"

  git archive --format=tar ${GIT_TAG} . | (cd ${BUILD_DIR}; tar xfp -)

  pushd ${SUBMODULE_PATH} > /dev/null
    git archive --format=tar ${SUBMODULE_SHA} . | (cd ${BUILD_DIR}/${SUBMODULE_PATH}; tar xfp -)
  popd > /dev/null

  git log -n 1 ${GIT_TAG} --pretty=format:"{ 'committer': '%an', 'sha': '${GIT_TAG}', 'revision': '%H', 'date_rfc': '%cD', 'date_epoc': '%ct' }" > ${VER_FILE}

  pushd ${PKG_PATH} > /dev/null
    tar -czf ${BUILD_TGZ} --numeric-owner ./${BUILD_FILE}
    rm -rf ./${BUILD_FILE}
  popd > /dev/null
popd > /dev/null

echo "Check the ${PKG_PATH}/${BUILD_TGZ} file"
