#!/bin/sh

set -x

if [ "$1" = "--help" ]
then
	echo ""
	echo "--help           this message"
	echo "--prefix=PATH    set the installation prefix"
	echo ""
	exit
fi

OPTION=`echo $1 | cut -f1 -d=`

if [ "$OPTION" = "--prefix" ]
then
	PREFIX=`echo $1 | cut -f2 -d=`
else
	PREFIX=/usr/local
fi

BUILD=`pwd`
cd src/freetds-0.82
./configure --prefix=$BUILD/freetds-0.82 --with-tdsver=8.0; make

cd $BUILD
cd src/ngx_http_viaduct
echo "s#FREETDS#$BUILD/src/freetds-0.82#g" > /tmp/sedfile.$$
if [ `uname` = "Darwin" ]
then
echo "s#VIADUCT_EXTRA_LIBS#-liconv#g" >> /tmp/sedfile.$$
elif [ `uname` = "Linux" ]
then
echo "s#VIADUCT_EXTRA_LIBS#-lrt#g" >> /tmp/sedfile.$$
else
echo "s#VIADUCT_EXTRA_LIBS##g" >> /tmp/sedfile.$$
fi
cat config.in | sed -f /tmp/sedfile.$$ > config
rm -f /tmp/sedfile.$$

cd $BUILD
cd src/nginx-0.7.22
./configure --prefix=$PREFIX --with-pcre=$BUILD/src/pcre-7.7/ --add-module=$BUILD/src/ngx_http_viaduct
make
make install

cd $PREFIX
patch -N -p0 -i $BUILD/patches/nginx.conf.patch
[ -d html ] || mkdir -p html
[ -d html/eg/ ] || mkdir -p html/eg
[ -d html/js ] || mkdir -p html/js
[ -d html/img ] || mkdir -p html/img
[ -d html/doc ] || mkdir -p html/doc
[ -d html/tablesorter ] || mkdir -p html/tablesorter
cp $BUILD/html/* html
cp $BUILD/html/js/* html/js
cp $BUILD/html/eg/* html/eg
cp $BUILD/html/img/* html/img
cp $BUILD/html/tablesorter/* html/tablesorter
cp $BUILD/doc/* html/doc
