#!/bin/sh

#set -x

if [ "$1" = "--help" ]
then
	echo ""
	echo "--help           this message"
	echo "--prefix=PATH    set the installation prefix"
	echo "--conf-file=PATH give the path to the default configuration file"
	echo ""
	exit
fi

OPTION=`echo $1 | cut -f1 -d=`

if [ "$OPTION" = "--prefix" ]
then
	PREFIX=`echo $1 | cut -f2 -d=`
else
	PREFIX=/usr/local
fi

OPTION=`echo $1 | cut -f1 -d=`

if [ "$OPTION" = "--conf-file" ]
then
	CONFPATH=`echo $2 | cut -f2 -d=`
else
	CONFPATH=conf/internal.conf
fi

TDSDIR=freetds-0.82
PCREDIR=pcre-7.8
NGXDIR=nginx-0.7.22

BUILD=`pwd`
cd src
rm -fr $PCREDIR
rm -fr $TDSDIR
rm -fr $NGXDIR
tar xvfz $PCREDIR.tgz
tar xvfz $TDSDIR.tgz
tar xvfz $NGXDIR.tar.gz
cd ..

# FreeTDS configuration
cd src/$TDSDIR
patch -N -p0 < ../../patches/freetds.patch
./configure --prefix=$BUILD/$TDSDIR --with-tdsver=8.0; make

# Viaduct module configuration
cd $BUILD
cd src/ngx_http_viaduct/src
echo "s#FREETDS#$BUILD/src/$TDSDIR#g" > /tmp/sedfile.$$
if [ `uname` = "Darwin" ]
then
  echo "s#VIADUCT_EXTRA_LIBS#-liconv#g" >> /tmp/sedfile.$$
elif [ `uname` = "Linux" ]
then
  echo "s#VIADUCT_EXTRA_LIBS#-lrt#g" >> /tmp/sedfile.$$
else
  echo "s#VIADUCT_EXTRA_LIBS##g" >> /tmp/sedfile.$$
fi
cat config.in | sed -f /tmp/sedfile.$$ > config
rm -f /tmp/sedfile.$$

# VIADUCT configuration
cd $BUILD
cd src/ngx_http_viaduct
./configure --with-nginx=$BUILD/src/$NGXDIR --with-freetds=$BUILD/src/$TDSDIR

# NGINX configuration
cd $BUILD
cd src/$NGXDIR
patch -N -p0 < ../../patches/wrapper.patch
patch -N -p0 < ../../patches/conffile.patch
HEAD=`grep '^"DEFAULT_CONF_IN"$' -n src/core/ngx_default_conf.h.in | cut -f1 -d:`
WC=`wc -l src/core/ngx_default_conf.h.in | awk '{print $1}'`
TAIL=`expr $WC - $HEAD`
HEAD=`expr $HEAD - 1`
head -$HEAD src/core/ngx_default_conf.h.in > src/core/ngx_default_conf.h
cat $CONFPATH | sed -e 's/^/"/' | sed -e 's/$/"/' >> src/core/ngx_default_conf.h
tail -$TAIL src/core/ngx_default_conf.h.in >> src/core/ngx_default_conf.h

./configure --prefix=$PREFIX --with-pcre=$BUILD/src/$PCREDIR/ --add-module=$BUILD/src/ngx_http_viaduct/src

make
make install
cd ../ngx_http_viaduct/src
make connector
cp connector $PREFIX/sbin

cd $PREFIX
patch -N -p0 -i $BUILD/patches/nginx.conf.patch
[ -d html ] || mkdir -p html
[ -d html/doc ] || mkdir -p html/doc
cp $BUILD/doc/* html/doc
cd $BUILD
tar --exclude='.svn' -c -f - html | (cd $PREFIX; tar xfp -)
