#!/bin/sh

#
# This build script now calls the autoconf build
#

#set -x

if [ "$1" = "--help" ]
then
	echo ""
	echo "--help           this message"
	echo "--prefix=PATH    set the installation prefix"
	echo "--conf-file=PATH give the path to the default configuration file"
	echo ""
	exit
fi

OPTION=`echo $1 | cut -f1 -d=`

if [ "$OPTION" = "--prefix" ]
then
	PREFIX=`echo $1 | cut -f2 -d=`
	shift
else
	PREFIX=/usr/local
fi

OPTION=`echo $1 | cut -f1 -d=`

if [ "$OPTION" = "--conf-file" ]
then
	CONFPATH=`echo $1 | cut -f2 -d=`
	shift
else
	CONFPATH=conf/internal.conf
fi

OPTION=`echo $1 | cut -f1 -d=`

if [ "$OPTION" = "--sql-dbtype" ]
then
	SQL_DBTYPE=`echo $1 | cut -f2 -d=`
	shift
else
	SQL_DBTYPE="mssql"
fi

if [ "${SQL_DBTYPE}" = "mssql" ]
then
  ./configure --prefix=$PREFIX --with-freetds
else
  ./configure --prefix=$PREFIX --with-mysql=/usr/local/mysql
fi

make
make install
